In [1]:
import pandas as pd

In [2]:
import os
os.listdir()

['.ipynb_checkpoints', 'Airbnb_Data_Preprocessing.ipynb']

In [3]:
import os
os.listdir("../data/raw")

['.ipynb_checkpoints', 'AB_NYC_2019.csv.zip']

In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/AB_NYC_2019.csv.zip")

In [5]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [6]:
df.shape

(48895, 16)

In [7]:
df.head()
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  str
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  str
 4   neighbourhood_group             48895 non-null  str
 5   neighbourhood                   48895 non-null  str
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  str
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  str
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), str(6)
memory usage: 9.9 MB

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [10]:
df.duplicated().sum()
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [11]:
df["name"] = df["name"].fillna("Unknown")
df["host_name"] = df["host_name"].fillna("Unknown")

In [12]:
df["reviews_per_month"] = df["reviews_per_month"].fillna(0)

In [13]:
df["last_review"] = df["last_review"].fillna("Not Reviewed")

In [14]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df=df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.dtypes

id                                  int64
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [19]:
df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

In [20]:
df.dtypes

id                                         int64
name                                         str
host_id                                    int64
host_name                                    str
neighbourhood_group                          str
neighbourhood                                str
latitude                                 float64
longitude                                float64
room_type                                    str
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[us]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
dtype: object

In [21]:
df[["price", "minimum_nights", "number_of_reviews",
    "reviews_per_month", "availability_365"]].describe()

,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365
count,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000
mean,152.720687,7.029962,23.274466,1.090910,112.781327
std,240.154170,20.510550,44.550582,1.597283,131.622289
min,0.000000,1.000000,0.000000,0.000000,0.000000
25%,69.000000,1.000000,1.000000,0.040000,0.000000
50%,106.000000,3.000000,5.000000,0.370000,45.000000
75%,175.000000,5.000000,24.000000,1.580000,227.000000
max,10000.000000,1250.000000,629.000000,58.500000,365.000000

In [22]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[(df["price"] < lower_bound) | (df["price"] > upper_bound)]

print("Number of price outliers:", len(outliers))

Lower bound: -90.0
Upper bound: 334.0
Number of price outliers: 2972

In [23]:
df["price"] = df["price"].clip(upper=upper_bound)

In [24]:
df["price"].max()

np.int64(334)

In [25]:
Q1 = df["minimum_nights"].quantile(0.25)
Q3 = df["minimum_nights"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df["minimum_nights"] < lower_bound) |
    (df["minimum_nights"] > upper_bound)
]

print("Number of minimum_nights outliers:", len(outliers))

Lower bound: -5.0
Upper bound: 11.0
Number of minimum_nights outliers: 6607

In [26]:
print("Listings with minimum_nights > 365:",
      (df["minimum_nights"] > 365).sum())

Listings with minimum_nights > 365: 14

In [27]:
df["minimum_nights"] = df["minimum_nights"].clip(upper=365)

In [28]:
df["minimum_nights"].max()

np.int64(365)

In [29]:
df[["price", "minimum_nights"]].describe()

              price  minimum_nights
count  48895.000000    48895.000000
mean     132.979753        6.942980
std       83.530504       17.530294
min        0.000000        1.000000
25%       69.000000        1.000000
50%      106.000000        3.000000
75%      175.000000        5.000000
max      334.000000      365.000000

In [30]:
Q1 = df["number_of_reviews"].quantile(0.25)
Q3 = df["number_of_reviews"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df["number_of_reviews"] < lower_bound) |
    (df["number_of_reviews"] > upper_bound)
]

print("Number of number_of_reviews outliers:", len(outliers))

Lower bound: -33.5
Upper bound: 58.5
Number of number_of_reviews outliers: 6021

In [31]:
df["number_of_reviews"].describe()

count    48895.000000
mean        23.274466
std         44.550582
min          0.000000
25%          1.000000
50%          5.000000
75%         24.000000
max        629.000000
Name: number_of_reviews, dtype: float64

In [32]:
Q1 = df["reviews_per_month"].quantile(0.25)
Q3 = df["reviews_per_month"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df["reviews_per_month"] < lower_bound) |
    (df["reviews_per_month"] > upper_bound)
]

print("Number of reviews_per_month outliers:", len(outliers))

Lower bound: -2.27
Upper bound: 3.89
Number of reviews_per_month outliers: 3312

In [33]:
df["reviews_per_month"].describe()

count    48895.000000
mean         1.090910
std          1.597283
min          0.000000
25%          0.040000
50%          0.370000
75%          1.580000
max         58.500000
Name: reviews_per_month, dtype: float64

In [34]:
Q1 = df["availability_365"].quantile(0.25)
Q3 = df["availability_365"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df["availability_365"] < lower_bound) |
    (df["availability_365"] > upper_bound)
]

print("Number of availability_365 outliers:", len(outliers))

Lower bound: -340.5
Upper bound: 567.5
Number of availability_365 outliers: 0

In [35]:
df["availability_365"].describe()

count    48895.000000
mean       112.781327
std        131.622289
min          0.000000
25%          0.000000
50%         45.000000
75%        227.000000
max        365.000000
Name: availability_365, dtype: float64

In [36]:
price_outliers = df[
    (df["price"] < lower_bound) |
    (df["price"] > upper_bound)
]

price_outliers["price"].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: price, dtype: float64

In [37]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

price_lower = Q1 - 1.5 * IQR
price_upper = Q3 + 1.5 * IQR

price_outliers = df[
    (df["price"] < price_lower) |
    (df["price"] > price_upper)
]

print("Price lower bound:", price_lower)
print("Price upper bound:", price_upper)
print("Number of price outliers:", len(price_outliers))

price_outliers["price"].describe()

Price lower bound: -90.0
Price upper bound: 334.0
Number of price outliers: 0

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: price, dtype: float64

In [38]:
df["price"] = df["price"].clip(upper=334)

print(df["price"].max())

334

In [39]:
import pandas as pd

df = pd.read_csv("../data/raw/AB_NYC_2019.csv.zip")

In [40]:
df["minimum_nights"] = df["minimum_nights"].clip(upper=365)

print(df["minimum_nights"].max())

365

In [41]:
print(df["reviews_per_month"].isnull().sum())

10052

In [42]:
df["reviews_per_month"] = df["reviews_per_month"].fillna(
    df["reviews_per_month"].median()
)

print(df["reviews_per_month"].isnull().sum())

0

In [43]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [44]:
df["last_review"].isnull().sum()

np.int64(10052)

In [45]:
df = df.drop(columns=["last_review"])

print(df.shape)

(48895, 15)

In [46]:
df.isnull().sum()

id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64

In [47]:
duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

In [48]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64

In [49]:
df.corr(numeric_only=True)

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
id,1.000000,0.588290,-0.003125,0.090908,0.010619,-0.012691,-0.319760,0.220804,0.133272,0.085468
host_id,0.588290,1.000000,0.020224,0.127055,0.015309,-0.019974,-0.140106,0.236499,0.154950,0.203492
latitude,-0.003125,0.020224,1.000000,0.084788,0.033939,0.028118,-0.015389,-0.014078,0.019517,-0.010983
longitude,0.090908,0.127055,0.084788,1.000000,-0.150019,-0.070785,0.059094,0.137153,-0.114713,0.082731
price,0.010619,0.015309,0.033939,-0.150019,1.000000,0.049921,-0.047954,-0.036814,0.057472,0.081829
minimum_nights,-0.012691,-0.019974,0.028118,-0.070785,0.049921,1.000000,-0.091764,-0.126202,0.150526,0.162278
number_of_reviews,-0.319760,-0.140106,-0.015389,0.059094,-0.047954,-0.091764,1.000000,0.568177,-0.072376,0.172028
reviews_per_month,0.220804,0.236499,-0.014078,0.137153,-0.036814,-0.126202,0.568177,1.000000,-0.027097,0.165954
calculated_host_listings_count,0.133272,0.154950,0.019517,-0.114713,0.057472,0.150526,-0.072376,-0.027097,1.000000,0.225701
availability_365,0.085468,0.203492,-0.010983,0.082731,0.081829,0.162278,0.172028,0.165954,0.225701,1.000000

In [50]:
df.isnull().sum()

id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64

In [51]:
df["name"] = df["name"].fillna("Unknown")
df["host_name"] = df["host_name"].fillna("Unknown")

In [52]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [53]:
df.shape

(48895, 15)

In [54]:
df.dtypes

id                                  int64
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [55]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0.72,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,1,0

In [56]:
print("Room types:")
print(df["room_type"].unique())

print("\nNeighbourhood groups:")
print(df["neighbourhood_group"].unique())

Room types:
<ArrowStringArray>
['Private room', 'Entire home/apt', 'Shared room']
Length: 3, dtype: str

Neighbourhood groups:
<ArrowStringArray>
['Brooklyn', 'Manhattan', 'Queens', 'Staten Island', 'Bronx']
Length: 5, dtype: str

In [57]:
print("Room type counts:")
print(df["room_type"].value_counts())

print("\nNeighbourhood group counts:")
print(df["neighbourhood_group"].value_counts())

Room type counts:
room_type
Entire home/apt    25409
Private room       22326
Shared room         1160
Name: count, dtype: int64

Neighbourhood group counts:
neighbourhood_group
Manhattan        21661
Brooklyn         20104
Queens            5666
Bronx             1091
Staten Island      373
Name: count, dtype: int64

In [58]:
duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

In [59]:
df.nunique()

id                                48895
name                              47906
host_id                           37457
host_name                         11453
neighbourhood_group                   5
neighbourhood                       221
latitude                          19048
longitude                         14718
room_type                             3
price                               674
minimum_nights                      101
number_of_reviews                   394
reviews_per_month                   937
calculated_host_listings_count       47
availability_365                    366
dtype: int64

In [24]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48895 non-null  str
 2   host_id                         48895 non-null  int64
 3   host_name                       48895 non-null  str
 4   neighbourhood_group             48895 non-null  str
 5   neighbourhood                   48895 non-null  str
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  str
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  reviews_per_month               48895 non-null  float64
 13  calculated_host_listings_count  48895 non-null  int64
 14  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), str(5)
memory usage: 9.2 MB

In [26]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,6.942980,23.274466,1.238930,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,17.530294,44.550582,1.520861,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.280000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,1.580000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,365.000000,629.000000,58.500000,327.000000,365.000000

In [27]:
print("Price statistics:")
print(df["price"].describe())

Price statistics:
count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [28]:
print("Minimum nights statistics:")
print(df["minimum_nights"].describe())

Minimum nights statistics:
count    48895.000000
mean         6.942980
std         17.530294
min          1.000000
25%          1.000000
50%          3.000000
75%          5.000000
max        365.000000
Name: minimum_nights, dtype: float64

In [30]:
print("Number of reviews statistics:")
print(df["number_of_reviews"].describe())

Number of reviews statistics:
count    48895.000000
mean        23.274466
std         44.550582
min          0.000000
25%          1.000000
50%          5.000000
75%         24.000000
max        629.000000
Name: number_of_reviews, dtype: float64

In [31]:
print("Reviews per month statistics:")
print(df["reviews_per_month"].describe())

Reviews per month statistics:
count    48895.000000
mean         1.238930
std          1.520861
min          0.010000
25%          0.280000
50%          0.720000
75%          1.580000
max         58.500000
Name: reviews_per_month, dtype: float64

In [32]:
print("Availability statistics:")
print(df["availability_365"].describe())

Availability statistics:
count    48895.000000
mean       112.781327
std        131.622289
min          0.000000
25%          0.000000
50%         45.000000
75%        227.000000
max        365.000000
Name: availability_365, dtype: float64

In [61]:
df["has_reviews"] = (df["number_of_reviews"] > 0).astype(int)

df["availability_category"] = pd.cut(
    df["availability_365"],
    bins=[-1, 90, 180, 365],
    labels=["Low", "Medium", "High"]
)

df["minimum_nights_category"] = pd.cut(
    df["minimum_nights"],
    bins=[0, 3, 7, 30, 365],
    labels=["Short Stay", "Weekly Stay", "Monthly Stay", "Long Stay"]
)

df["host_activity_level"] = pd.cut(
    df["calculated_host_listings_count"],
    bins=[0, 1, 5, 10, float("inf")],
    labels=["Single Listing", "Small Host", "Medium Host", "Large Host"]
)

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,has_reviews,availability_category,minimum_nights_category,host_activity_level
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,6,365,1,High,Short Stay,Medium Host
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,2,355,1,High,Short Stay,Small Host
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,0.72,1,365,0,High,Short Stay,Single Listing
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,1,194,1,High,Short Stay,Single Listing
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,1,0,1,Low,Monthly Stay,Single Listing

In [62]:
df[[
    "has_reviews",
    "availability_category",
    "minimum_nights_category",
    "host_activity_level"
]].head()

,has_reviews,availability_category,minimum_nights_category,host_activity_level
0,1,High,Short Stay,Medium Host
1,1,High,Short Stay,Small Host
2,0,High,Short Stay,Single Listing
3,1,High,Short Stay,Single Listing
4,1,Low,Monthly Stay,Single Listing

In [63]:
print("Dataset shape:", df.shape)

print("\nTotal missing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Dataset shape: (48895, 19)

Total missing values:
0

Duplicate rows:
0

Data types:
id                                   int64
name                                   str
host_id                              int64
host_name                              str
neighbourhood_group                    str
neighbourhood                          str
latitude                           float64
longitude                          float64
room_type                              str
price                                int64
minimum_nights                       int64
number_of_reviews                    int64
reviews_per_month                  float64
calculated_host_listings_count       int64
availability_365                     int64
has_reviews                          int64
availability_category             category
minimum_nights_category           category
host_activity_level               category
dtype: object

In [64]:
import os

os.makedirs("../data/processed", exist_ok=True)

df.to_csv("../data/processed/clean_airbnb.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [65]:
import os

print(os.path.exists("../data/processed/clean_airbnb.csv"))

True

In [66]:
print("FINAL DATASET SUMMARY")
print("---------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("\nColumns:")
print(list(df.columns))

FINAL DATASET SUMMARY
---------------------
Rows: 48895
Columns: 19
Missing values: 0
Duplicate rows: 0

Columns:
['id', 'name', 'host_id', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'has_reviews', 'availability_category', 'minimum_nights_category', 'host_activity_level']